title: Jekyll Tailwind Template
description: Basic Jekyll site template using Tailwind CSS with PostCSS
author: Kvído Potápník

url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag # check https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md for configuration options
  - jekyll-sitemap
  - jekyll-postcss

postcss:
  cache: false

permalink: pretty

source: src/

exclude: [
  .gitignore,
  styles/index.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  tailwind.config.js,
  README.md,
  build/,
]
